In [1]:
import numpy as np


Functions

In [3]:
print(np.arange(1,6,))
print(np.zeros((3, 2),dtype=int))
print(np.ones((3,4),dtype=int))
print(np.arange(6).reshape(2,3))

[1 2 3 4 5]
[[0 0]
 [0 0]
 [0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 1 2]
 [3 4 5]]


In [4]:
arr=np.repeat([[3,7]],5,axis=0) 
print(arr)

[[3 7]
 [3 7]
 [3 7]
 [3 7]
 [3 7]]


In [5]:
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])
c=np.concatenate([arr,arr1])
print(c)

[1 2 3 4 5 6 7 8]


Opration

In [6]:
arr=np.array([[10,20,30,40],[50,60,70,80]])                          
print(arr.dtype)#datatype
print(np.shape(arr))#find row and column
print(np.size(arr))#size
print(np.ndim(arr))#find dimansional                  


import numpy as np
arr1=np.array([10,20,30,40] ,ndmin=5) 
print(arr1)
print(arr1.ndim) 

int64
(2, 4)
8
2
[[[[[10 20 30 40]]]]]
5


Indexing


In [7]:
arr=np.array([1,2,3,4,5,6])
print(arr[0:4])
print(arr[0:6:2])
print(arr[:-1])

[1 2 3 4]
[1 3 5]
[1 2 3 4 5]


In [8]:
arr=np.array([[[2,3],[4,5]],[[2,8],[3,6]]])
print(arr[0,1,0])
print(arr[1,-1,0])
      

4
3


more function


In [9]:
import numpy as np
arr=np.array([1,2,3,5]) 
pow=np.power(arr,[1,2,4,3])
print(pow)

[  1   4  81 125]


In [10]:
arr=np.array([1,2,3,4])
arr1=np.array([5,6,7,8])
# d=np.diff(arr)
d=np.diff((arr,arr1),axis=0)
print(d)

[[4 4 4 4]]


In [11]:
arr=np.array([1,6])
arr1=np.array([5,6])
c=np.cross(arr,arr1)
print(c)

-24


C:\Users\Dell\AppData\Local\Temp\ipykernel_13412\923981186.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  c=np.cross(arr,arr1)


In [12]:
n1=[2,4,6,8]
n2=[1,2,3,5]
n=np.array([n1,n2])
print(n)

[[2 4 6 8]
 [1 2 3 5]]


In [13]:
n1=[2,4,6,8]
n2=[1,2,3,5]
n=np.array([n1,n2])
print(n.flatten("C"))

[2 4 6 8 1 2 3 5]


In [14]:
n1=[2,4,6,8]
n2=[1,2,3,5]
n=np.array([n1,n2])
print(n.sum(axis=0))

[ 3  6  9 13]


In [15]:
n1=[2,4,6,np.nan]
n2=[1,2,3,5]
n=np.array([n1,n2])
print(np.nansum(n,axis=1))

[12. 11.]


In [16]:
n1=[2,6,7,8]
n2=[3,5,6,7]
n=np.array([n1,n2])
print(np.cumsum(n))

[ 2  8 15 23 26 31 37 44]


In [17]:
n1=[2,6,7,8]
n2=[3,5,6,7]
n=np.array([n1,n2])
print(np.cumprod(n,axis=0))

[[ 2  6  7  8]
 [ 6 30 42 56]]


Iterating Numpy Array


In [18]:
arr=np.array([1,2,6,8,9,7])
for x in arr:
 print(x)


1
2
6
8
9
7


In [19]:
arr=np.array([[[2,3],[4,5]],[[2,8],[3,6]]])
# for i in arr:
#     for j in i:
#         for k in j:
#             print(k)

for i in np.nditer(arr):
    print(i)

2
3
4
5
2
8
3
6


In [20]:
# arr=np.array([1,2,6,8,9,7])
arr=np.array([[[1,2,6,8,9,7],[2,8,4,9,6,1]],[[1,2,6,8,9,7],[2,8,4,9,6,1]]])
for ind, i in np.ndenumerate(arr):
    print(ind,i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 6
(0, 0, 3) 8
(0, 0, 4) 9
(0, 0, 5) 7
(0, 1, 0) 2
(0, 1, 1) 8
(0, 1, 2) 4
(0, 1, 3) 9
(0, 1, 4) 6
(0, 1, 5) 1
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 6
(1, 0, 3) 8
(1, 0, 4) 9
(1, 0, 5) 7
(1, 1, 0) 2
(1, 1, 1) 8
(1, 1, 2) 4
(1, 1, 3) 9
(1, 1, 4) 6
(1, 1, 5) 1


Copy vs View


In [21]:
arr=np.array([1,3,4,5,6])
c=np.copy(arr)
arr[2]=9
print("original :",arr)
print("copy:",c)

original : [1 3 9 5 6]
copy: [1 3 4 5 6]


In [22]:
arr=np.array([1,3,4,5,6])
v=arr.view()
arr[2]=9
print("original :",arr)
print("view:",v)

original : [1 3 9 5 6]
view: [1 3 9 5 6]


Spliting function


In [23]:
arr=np.array([1,3,4,5,6,7,8])
sp=np.array_split(arr,6)
print(sp)

[array([1, 3]), array([4]), array([5]), array([6]), array([7]), array([8])]


In [24]:
arr=np.array([[[1,3,4],[5,6,7]],[[4,5,6],[8,7,8]]])
sp=np.array_split(arr,3,axis=1)
print(sp)

[array([[[1, 3, 4]],

       [[4, 5, 6]]]), array([[[5, 6, 7]],

       [[8, 7, 8]]]), array([], shape=(2, 0, 3), dtype=int64)]


Short ,Search and Filter

In [25]:
#arr=np.array([1,3,9,5,21,72,8])
arr=np.array([[[1,3,4],[5,6,7]],[[4,5,6],[8,7,8]]])
s=np.sort(arr, axis=1)
print(s)

[[[1 3 4]
  [5 6 7]]

 [[4 5 6]
  [8 7 8]]]


In [26]:
arr=np.array([1,3,4,5,6,7,8])
sp1=np.where(arr==6)
sp2=np.where(arr>6)
sp3=np.where(arr%2==0)
print(sp1)
print(sp2)
print(sp3)

(array([4]),)
(array([5, 6]),)
(array([2, 4, 6]),)


In [27]:
arr=np.array([1,3,4,5,6,7,8])
ss=np.searchsorted(arr,5)
print(ss)

3


In [28]:
arr=np.array([2,4,5,6,7])
#fa=[True,False,True,False]
#fa=arr%2==0
fa=arr%2!=0
new=arr[fa]
print(new)

[5 7]


Shuffle Unique Resize and Ravel

In [29]:
arr=np.array([1,3,4,5,6,9])
print(arr)
np.random.shuffle(arr)
print(arr)


[1 3 4 5 6 9]
[9 4 5 1 6 3]


In [30]:
arr=np.array([1,3,1,4,2,6,5,6,9,7,7])
print(arr)
print(np.unique(arr))

[1 3 1 4 2 6 5 6 9 7 7]
[1 2 3 4 5 6 7 9]


In [31]:
arr=np.array([1,3,1,4,2,6,5,6,9,7,7])
print(arr)
print(np.resize(arr,(3,2)))

[1 3 1 4 2 6 5 6 9 7 7]
[[1 3]
 [1 4]
 [2 6]]


In [32]:
arr=np.array([[[1,3,4],[5,6,7]],[[4,5,6],[8,7,8]]])
print(arr)
print(np.ravel(arr))

[[[1 3 4]
  [5 6 7]]

 [[4 5 6]
  [8 7 8]]]
[1 3 4 5 6 7 4 5 6 8 7 8]


Inset & Delete

In [33]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.insert(arr,[2,4],[30,60]))

[10 20 30 40 50]
[10 20 30 30 40 60 50]


In [34]:
arr=np.array([10,20,30,40,50])
print(arr)
print(np.delete(arr,[2,4]))

[10 20 30 40 50]
[10 20 40]


Arithmatic Operataion


In [35]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,4,6,8,9])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr2//arr1)
print(arr1**arr2)

[ 3  6  9 12 14]
[-1 -2 -3 -4 -4]
[ 2  8 18 32 45]
[0.5        0.5        0.5        0.5        0.55555556]
[2 2 2 2 1]
[      1      16     729   65536 1953125]


Matrics


In [36]:
mat1=np.matrix([[2,3],[4,6]])
mat2=np.matrix([[2,7],[7,9]])
print(np.dot(mat1,mat2))
print(type(mat1))


[[25 41]
 [50 82]]
<class 'numpy.matrix'>


In [37]:
mat1=np.matrix([[2,3,7],[4,6,9],[5,6,3]])
print(mat1)
print("using trasport")
print(np.transpose(mat1))
print("using T method")
print(mat1.T)


[[2 3 7]
 [4 6 9]
 [5 6 3]]
using trasport
[[2 4 5]
 [3 6 6]
 [7 9 3]]
using T method
[[2 4 5]
 [3 6 6]
 [7 9 3]]


In [38]:
mat1=np.matrix([[2,3,7],[4,6,9],[5,6,3]])
print(mat1.diagonal())
print(mat1.trace())

[[2 6 3]]
[[11]]


In [39]:
#Determinate
mat1=np.matrix([[2,3,7],[4,6,9],[5,6,3]])
print(np.linalg.det(mat1))
print(np.linalg.matrix_rank(mat1))
print(np.linalg.inv(mat1))
print(np.linalg.pinv(mat1))

-14.999999999999993
3
[[ 2.4        -2.2         1.        ]
 [-2.2         1.93333333 -0.66666667]
 [ 0.4        -0.2         0.        ]]
[[ 2.40000000e+00 -2.20000000e+00  1.00000000e+00]
 [-2.20000000e+00  1.93333333e+00 -6.66666667e-01]
 [ 4.00000000e-01 -2.00000000e-01 -6.89479182e-16]]


In [40]:
import numpy 
import random

In [41]:
from numpy import random

x = random.randint(100)

print(x)


24


In [42]:
from numpy import random

x = random.rand()

print(x)

0.7778221823637164


In [ ]:
num = [1,2,3]
y = [num*2 for num in x]
print(y)

[2, 4, 6]
