Series with List

In [2]:
import pandas as pd
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
list_data=[2,4,6,8,10]
list_index=["a","b","c","d","e"]
var=pd.Series(data=list_data,index=list_index,dtype=float)
var

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float64

In [4]:
type(var)

pandas.core.series.Series

Series with Dictionary

In [5]:
dict={"max":45,"min":10,"avg":30}
pd.Series(data=dict)

max    45
min    10
avg    30
dtype: int64

In [6]:
var=pd.Series(data=dict, index={"mix","max","mode"}, dtype=float)
var

max     45.0
mode     NaN
mix      NaN
dtype: float64

Series with NumPy Array

In [7]:
import numpy as np
arr1=np.array([1,3.3,5,7.9,9])
arr2=np.array(["a","b","c","d","e"])
var=pd.Series(data=arr1,index=arr2)
var

a    1.0
b    3.3
c    5.0
d    7.9
e    9.0
dtype: float64

In [8]:
type(var)

pandas.core.series.Series

Object types Series

In [9]:
pd.Series(["hello",20,10.90,True])


0    hello
1       20
2     10.9
3     True
dtype: object

In [10]:
var=pd.Series(["hello",20,10.90,True])
var[0]
print(type(var[0]))
print(type(var[1]))
print(type(var[2]))
print(type(var[3]))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [11]:
pd.Series([sum,type,max])

0    <built-in function sum>
1             <class 'type'>
2    <built-in function max>
dtype: object

Primary Features of pandas Series

In [12]:
import pandas as pd
var=pd.Series([10,20,30,40,50,60,70])
var


0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [13]:
var.axes
var.size
var.ndim
var.head() #first five value
var.tail() #last five value

2    30
3    40
4    50
5    60
6    70
dtype: int64

Most Applied method

In [14]:
list_data=[2,4,6,8,10]
list_index=["b","d","c","a","e"]
var=pd.Series(data=list_data,index=list_index)
var

b     2
d     4
c     6
a     8
e    10
dtype: int64

In [15]:
var.sort_index()

a     8
b     2
c     6
d     4
e    10
dtype: int64

In [16]:
var.sort_values()

b     2
d     4
c     6
a     8
e    10
dtype: int64

In [17]:
[var.isin([6,2,10])]

[b     True
 d    False
 c     True
 a    False
 e     True
 dtype: bool]

In [18]:
var[var.isin([6,2,10])]

b     2
c     6
e    10
dtype: int64

In [19]:
var.values

array([ 2,  4,  6,  8, 10])

In [20]:
[ i for i in var.values] 

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]

In [21]:
var.index

Index(['b', 'd', 'c', 'a', 'e'], dtype='object')

In [22]:
[ i for i in var.index] 

['b', 'd', 'c', 'a', 'e']

In [23]:
var.items

<bound method Series.items of b     2
d     4
c     6
a     8
e    10
dtype: int64>

In [24]:
var.items()

In [25]:
for index, value in var.items():
    print(index,"-",value)

b - 2
d - 4
c - 6
a - 8
e - 10


Indexing and Slicing

In [26]:
sre=pd.Series(data=["Max",21,"Btech","lucknow"], index=["Name","Age","Course","City"])
sre

Name          Max
Age            21
Course      Btech
City      lucknow
dtype: object

In [27]:
sre[1]

C:\Users\Dell\AppData\Local\Temp\ipykernel_7328\3497254338.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sre[1]


21

In [28]:
sre[1:3:3]

Age    21
dtype: object

Data Frame With List

In [29]:
list=[5,10,7,9]
list

[5, 10, 7, 9]

In [30]:
pd.DataFrame(data=list,columns=["values"],dtype="float")

values
0     5.0
1    10.0
2     7.0
3     9.0

Data Frame With Numpy Array

In [31]:
arr=np.random.randint(0,50,(4,4))
arr

array([[35, 35, 41, 42],
       [ 4, 28, 23, 37],
       [31, 24, 37, 33],
       [26, 40, 19, 33]], dtype=int32)

In [32]:
pd.DataFrame(arr,index=["a","b","c","d"],columns=["val1","val2","val3","val4"])

val1  val2  val3  val4
a    35    35    41    42
b     4    28    23    37
c    31    24    37    33
d    26    40    19    33

Data Frame With Dictionary

In [33]:
x=np.random.randint(10,50, size=7)
x

array([17, 23, 49, 11, 25, 40, 12], dtype=int32)

In [34]:
x=np.random.randint(10,50, size=7)
y=np.random.randint(10,50, size=7)
z=np.random.randint(10,50, size=7)

dict_ex={"val1":x,"val2":y,"var3":z}
dict_ex

{'val1': array([37, 35, 33, 33, 49, 36, 38], dtype=int32),
 'val2': array([40, 23, 23, 19, 45, 16, 28], dtype=int32),
 'var3': array([21, 42, 21, 22, 17, 38, 46], dtype=int32)}

In [35]:
dff=pd.DataFrame(dict_ex)
dff

val1  val2  var3
0    37    40    21
1    35    23    42
2    33    23    21
3    33    19    22
4    49    45    17
5    36    16    38
6    38    28    46

Properties of Pandas Dataframes

In [36]:
dff.head()

val1  val2  var3
0    37    40    21
1    35    23    42
2    33    23    21
3    33    19    22
4    49    45    17

In [37]:
dff.columns

Index(['val1', 'val2', 'var3'], dtype='object')

In [38]:
dff.index

RangeIndex(start=0, stop=7, step=1)

In [39]:
dff.columns=["n1","n2","n3"]
dff

n1  n2  n3
0  37  40  21
1  35  23  42
2  33  23  21
3  33  19  22
4  49  45  17
5  36  16  38
6  38  28  46

In [40]:
dff.values

array([[37, 40, 21],
       [35, 23, 42],
       [33, 23, 21],
       [33, 19, 22],
       [49, 45, 17],
       [36, 16, 38],
       [38, 28, 46]], dtype=int32)

In [41]:
dff.size

21

Selection Operation in DataFrame

In [42]:
a=np.random.seed(101)
df=pd.DataFrame(data=np.random.randn(6,5),index="A B C D E F".split(),columns=["v1 v2 v3 v4 v5".split()])
df

v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [43]:
df["v1"][3:5]

v1
D  0.955057
E  0.302665

In [44]:
df[["v1","v5"]]

v1        v5
A  2.706850  0.651118
B -0.319318  0.740122
C  0.528813 -0.933237
D  0.955057  0.683509
E  0.302665 -0.134841
F  0.390528  0.072960

In [45]:
df

v1        v2        v3        v4        v5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [46]:
var=["v2","v3"]
df[var]

v2        v3
A  0.628133  0.907969
B -0.848077  0.605965
C -0.589001  0.188695
D  0.190794  1.978757
E  1.693723 -1.706086
F  0.166905  0.184502

In [47]:
df[3:5][["v1","v5"]]

v1        v5
D  0.955057  0.683509
E  0.302665 -0.134841

Element Selectiopn in Data frams

In [51]:
np.random.seed(101)
arr1 = np.random.randint(10,50,(8,5))
df=pd.DataFrame(data= arr1 ,index="A B C D E F G H".split(),columns=" V1 V2 V3 V4 V5".split())
df

V1  V2  V3  V4  V5
A  41  21  27  16  33
B  21  19  23  14  38
C  10  15  22  39  29
D  18  39  44  18  29
E  20  22  41  33  10
F  19  18  46  29  45
G  38  17  20  49  48
H  19  28  17  49  25

1-LOC =label base
used to select element from the dataframe
opertae with index'name
first and last element are include in the slicing

In [49]:
df.loc["A":"D"]

Empty DataFrame
Columns: [V1, V2, V3, V4, V5]
Index: []

In [50]:
df.loc["C","V4"]

KeyError: 'C'

In [50]:
df.loc["C":"G",["V3"]]

V3
C  22
D  44
E  41
F  46
G  20

2-IlOc ={integer location base indexing}

In [51]:
df.iloc[0:4]

V1  V2  V3  V4  V5
A  41  21  27  16  33
B  21  19  23  14  38
C  10  15  22  39  29
D  18  39  44  18  29

In [52]:
df.iloc[2,3]

np.int32(39)

In [53]:
df.iloc[2:5,[3]]

V4
C  39
D  18
E  33

In [54]:
df.iloc[2:5][["V3"]]

V3
C  22
D  44
E  41

In [55]:
df

V1  V2  V3  V4  V5
A  41  21  27  16  33
B  21  19  23  14  38
C  10  15  22  39  29
D  18  39  44  18  29
E  20  22  41  33  10
F  19  18  46  29  45
G  38  17  20  49  48
H  19  28  17  49  25

In [56]:
df.loc["C":"H","V2":"V4"]

V2  V3  V4
C  15  22  39
D  39  44  18
E  22  41  33
F  18  46  29
G  17  20  49
H  28  17  49

In [57]:
df.iloc[2:5,1:4]

V2  V3  V4
C  15  22  39
D  39  44  18
E  22  41  33

In [58]:
df.iloc[2:5,1:4].loc["E":"G",["V3"]]

V3
E  41

 SELECT With Conditional Opertation 

In [59]:
np.random.seed(101)
arr=np.random.randint(10,80,(8,6))
df=pd.DataFrame(data= arr1 ,index="A B C D E F G H".split(),columns=" V1 V2 V3 V4 V5".split())
df

V1  V2  V3  V4  V5
A  41  21  27  16  33
B  21  19  23  14  38
C  10  15  22  39  29
D  18  39  44  18  29
E  20  22  41  33  10
F  19  18  46  29  45
G  38  17  20  49  48
H  19  28  17  49  25

In [60]:
df>20

V1     V2     V3     V4     V5
A   True   True   True  False   True
B   True  False   True  False   True
C  False  False   True   True   True
D  False   True   True  False   True
E  False   True   True   True  False
F  False  False   True   True   True
G   True  False  False   True   True
H  False   True  False   True   True

In [61]:
df[df>20]

V1    V2    V3    V4    V5
A  41.0  21.0  27.0   NaN  33.0
B  21.0   NaN  23.0   NaN  38.0
C   NaN   NaN  22.0  39.0  29.0
D   NaN  39.0  44.0   NaN  29.0
E   NaN  22.0  41.0  33.0   NaN
F   NaN   NaN  46.0  29.0  45.0
G  38.0   NaN   NaN  49.0  48.0
H   NaN  28.0   NaN  49.0  25.0

In [62]:
df[df["V1"]<20][["V3"]]

V3
C  22
D  44
F  46
H  17

In [63]:
df

V1  V2  V3  V4  V5
A  41  21  27  16  33
B  21  19  23  14  38
C  10  15  22  39  29
D  18  39  44  18  29
E  20  22  41  33  10
F  19  18  46  29  45
G  38  17  20  49  48
H  19  28  17  49  25

And

In [64]:
df[(df["V2"] > 20)&(df["V4"]  < 19) ]

V1  V2  V3  V4  V5
A  41  21  27  16  33
D  18  39  44  18  29

OR

In [65]:
df[(df<35)| (df["V5"]>20)]

V1    V2    V3    V4    V5
A   NaN  21.0  27.0  16.0  33.0
B  21.0  19.0  23.0  14.0   NaN
C  10.0  15.0  22.0   NaN  29.0
D  18.0   NaN   NaN  18.0  29.0
E  20.0  22.0   NaN  33.0  10.0
F  19.0  18.0   NaN  29.0   NaN
G   NaN  17.0  20.0   NaN   NaN
H  19.0  28.0  17.0   NaN  25.0

In [66]:
df.loc[df.V2 >25,["V1","V2"] ]

V1  V2
D  18  39
H  19  28

Adding Columns to Data Frame

In [67]:
import numpy as np
x = np.arange(0,28).reshape(7,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [68]:
df=pd.DataFrame(data=x,columns="V1 V2 V3 V4".split())
df

V1  V2  V3  V4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23
6  24  25  26  27

In [69]:
df["V5"]=df["V1"]+df["V3"]
df

V1  V2  V3  V4  V5
0   0   1   2   3   2
1   4   5   6   7  10
2   8   9  10  11  18
3  12  13  14  15  26
4  16  17  18  19  34
5  20  21  22  23  42
6  24  25  26  27  50

In [70]:
df["V6"]=df["V3"]*df["V4"]
df

V1  V2  V3  V4  V5   V6
0   0   1   2   3   2    6
1   4   5   6   7  10   42
2   8   9  10  11  18  110
3  12  13  14  15  26  210
4  16  17  18  19  34  342
5  20  21  22  23  42  506
6  24  25  26  27  50  702

In [71]:
df["V7"]=np.arange(28,35)
df

V1  V2  V3  V4  V5   V6  V7
0   0   1   2   3   2    6  28
1   4   5   6   7  10   42  29
2   8   9  10  11  18  110  30
3  12  13  14  15  26  210  31
4  16  17  18  19  34  342  32
5  20  21  22  23  42  506  33
6  24  25  26  27  50  702  34

Removing Coloumn

In [72]:

df

V1  V2  V3  V4  V5   V6  V7
0   0   1   2   3   2    6  28
1   4   5   6   7  10   42  29
2   8   9  10  11  18  110  30
3  12  13  14  15  26  210  31
4  16  17  18  19  34  342  32
5  20  21  22  23  42  506  33
6  24  25  26  27  50  702  34

In [73]:
df.drop(["V4","V7"],axis=1)

V1  V2  V3  V5   V6
0   0   1   2   2    6
1   4   5   6  10   42
2   8   9  10  18  110
3  12  13  14  26  210
4  16  17  18  34  342
5  20  21  22  42  506
6  24  25  26  50  702

In [74]:
df.drop([2,5],axis=0)

V1  V2  V3  V4  V5   V6  V7
0   0   1   2   3   2    6  28
1   4   5   6   7  10   42  29
3  12  13  14  15  26  210  31
4  16  17  18  19  34  342  32
6  24  25  26  27  50  702  34

NULL Values In Dataframe

In [75]:
df = pd.DataFrame({'V1':[2,4,np.nan,6,np.nan,8,np.nan],
                   'V2':[2,43,66,np.nan,np.nan,87,190],
                 'V3':["sec1","sec2","sec3","sec4","sec5","sec6","sec7"]})
df

V1     V2    V3
0  2.0    2.0  sec1
1  4.0   43.0  sec2
2  NaN   66.0  sec3
3  6.0    NaN  sec4
4  NaN    NaN  sec5
5  8.0   87.0  sec6
6  NaN  190.0  sec7

In [76]:
df.isnull()

V1     V2     V3
0  False  False  False
1  False  False  False
2   True  False  False
3  False   True  False
4   True   True  False
5  False  False  False
6   True  False  False

In [77]:
df.isnull().sum()

V1    3
V2    2
V3    0
dtype: int64

In [78]:
len(df)

7

In [79]:
df.isnull().sum()/len(df)*100

V1    42.857143
V2    28.571429
V3     0.000000
dtype: float64

In [80]:
df.notnull()

V1     V2    V3
0   True   True  True
1   True   True  True
2  False   True  True
3   True  False  True
4  False  False  True
5   True   True  True
6  False   True  True

In [81]:
df.notnull().sum()

V1    4
V2    5
V3    7
dtype: int64

Droping Null Value Dropna


In [82]:
df

V1     V2    V3
0  2.0    2.0  sec1
1  4.0   43.0  sec2
2  NaN   66.0  sec3
3  6.0    NaN  sec4
4  NaN    NaN  sec5
5  8.0   87.0  sec6
6  NaN  190.0  sec7

In [83]:
df.dropna()
df.dropna(axis=1)

V3
0  sec1
1  sec2
2  sec3
3  sec4
4  sec5
5  sec6
6  sec7

In [84]:
df["V4"]=np.nan
df

V1     V2    V3  V4
0  2.0    2.0  sec1 NaN
1  4.0   43.0  sec2 NaN
2  NaN   66.0  sec3 NaN
3  6.0    NaN  sec4 NaN
4  NaN    NaN  sec5 NaN
5  8.0   87.0  sec6 NaN
6  NaN  190.0  sec7 NaN

In [85]:
df.dropna(how="all" ,axis=1)

V1     V2    V3
0  2.0    2.0  sec1
1  4.0   43.0  sec2
2  NaN   66.0  sec3
3  6.0    NaN  sec4
4  NaN    NaN  sec5
5  8.0   87.0  sec6
6  NaN  190.0  sec7

Filling Null Value = fillna()

In [86]:
df

V1     V2    V3  V4
0  2.0    2.0  sec1 NaN
1  4.0   43.0  sec2 NaN
2  NaN   66.0  sec3 NaN
3  6.0    NaN  sec4 NaN
4  NaN    NaN  sec5 NaN
5  8.0   87.0  sec6 NaN
6  NaN  190.0  sec7 NaN

In [87]:
df.fillna(10)

V1     V2    V3    V4
0   2.0    2.0  sec1  10.0
1   4.0   43.0  sec2  10.0
2  10.0   66.0  sec3  10.0
3   6.0   10.0  sec4  10.0
4  10.0   10.0  sec5  10.0
5   8.0   87.0  sec6  10.0
6  10.0  190.0  sec7  10.0

In [88]:
a=1000
df.fillna(a)

V1      V2    V3      V4
0     2.0     2.0  sec1  1000.0
1     4.0    43.0  sec2  1000.0
2  1000.0    66.0  sec3  1000.0
3     6.0  1000.0  sec4  1000.0
4  1000.0  1000.0  sec5  1000.0
5     8.0    87.0  sec6  1000.0
6  1000.0   190.0  sec7  1000.0

In [89]:
df["V3"][0::2]=np.nan
df

C:\Users\Dell\AppData\Local\Temp\ipykernel_17888\3343539774.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["V3"][0::2]=np.nan
C:\Users\Dell\AppData\Local\Temp\ipykernel_17888\3343539774.py:1: SettingWithCopyWarning: 
A value is tryin

V1     V2    V3  V4
0  2.0    2.0   NaN NaN
1  4.0   43.0  sec2 NaN
2  NaN   66.0   NaN NaN
3  6.0    NaN  sec4 NaN
4  NaN    NaN   NaN NaN
5  8.0   87.0  sec6 NaN
6  NaN  190.0   NaN NaN

In [90]:
df.drop("V4",axis=1)

V1     V2    V3
0  2.0    2.0   NaN
1  4.0   43.0  sec2
2  NaN   66.0   NaN
3  6.0    NaN  sec4
4  NaN    NaN   NaN
5  8.0   87.0  sec6
6  NaN  190.0   NaN

method of fillna

In [91]:
df.fillna(method="ffill")
df.fillna(method="pad")
df.fillna(method="bfill")
df.fillna(method="backfill")


C:\Users\Dell\AppData\Local\Temp\ipykernel_17888\3472064821.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")
C:\Users\Dell\AppData\Local\Temp\ipykernel_17888\3472064821.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="pad")
C:\Users\Dell\AppData\Local\Temp\ipykernel_17888\3472064821.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")
C:\Users\Dell\AppData\Local\Temp\ipykernel_17888\3472064821.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="backfill")


V1     V2    V3  V4
0  2.0    2.0  sec2 NaN
1  4.0   43.0  sec2 NaN
2  6.0   66.0  sec4 NaN
3  6.0   87.0  sec4 NaN
4  8.0   87.0  sec6 NaN
5  8.0   87.0  sec6 NaN
6  NaN  190.0   NaN NaN

In [92]:
np.random.seed(101)
df=pd.DataFrame(data=np.random.randn(6,5),index="A B C D E F".split(),columns="V1 V2 V3 V4 V5".split())
df

V1        V2        V3        V4        V5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [93]:
df.reset_index()

index        V1        V2        V3        V4        V5
0     A  2.706850  0.628133  0.907969  0.503826  0.651118
1     B -0.319318 -0.848077  0.605965 -2.018168  0.740122
2     C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
3     D  0.955057  0.190794  1.978757  2.605967  0.683509
4     E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
5     F  0.390528  0.166905  0.184502  0.807706  0.072960

In [94]:
df

V1        V2        V3        V4        V5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [95]:
ex= "A B HI NA V VE"

In [96]:
ex=("A B HI NA V VE").split()

In [97]:
ex

['A', 'B', 'HI', 'NA', 'V', 'VE']

In [98]:
df["new_index"]=ex

In [99]:
df

V1        V2        V3        V4        V5 new_index
A  2.706850  0.628133  0.907969  0.503826  0.651118         A
B -0.319318 -0.848077  0.605965 -2.018168  0.740122         B
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237        HI
D  0.955057  0.190794  1.978757  2.605967  0.683509        NA
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841         V
F  0.390528  0.166905  0.184502  0.807706  0.072960        VE

In [104]:
df.set_index("new_index")


V1        V2        V3        V4        V5
new_index                                                  
A          2.706850  0.628133  0.907969  0.503826  0.651118
B         -0.319318 -0.848077  0.605965 -2.018168  0.740122
HI         0.528813 -0.589001  0.188695 -0.758872 -0.933237
NA         0.955057  0.190794  1.978757  2.605967  0.683509
V          0.302665  1.693723 -1.706086 -1.159119 -0.134841
VE         0.390528  0.166905  0.184502  0.807706  0.072960

In [ ]:
import pandas as pd
import openpyxl  # This is the key step after installation

# Read data from Excel file
df = pd.read_excel('textbook2.xlsx')

# Display the DataFrame
print(df)


ModuleNotFoundError: No module named 'openpyxl'

: 